// <auto-generated />
using System;
using GerenciadorDeLivros.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GerenciadorDeLivros.Migrations.Emprestimo
{
    [DbContext(typeof(EmprestimoContext))]
    [Migration("20250116131829_CreateEmprestimoTable")]
    partial class CreateEmprestimoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorDeLivros.Model.Emprestimo", b =>
                {
                    b.Property<int>("EmprestimoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("emprestimo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmprestimoId"));

                    b.Property<DateOnly>("DataDaDevolucao")
                        .HasColumnType("date")
                        .HasColumnName("data_da_devolucao");

                    b.Property<DateOnly>("DataDoEmprestimo")
                        .HasColumnType("date")
                        .HasColumnName("data_do_emprestimo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("LivroId")
                        .HasColumnType("integer")
                        .HasColumnName("livro_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nome");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision")
                        .HasColumnName("valor");

                    b.HasKey("EmprestimoId");

                    b.ToTable("emprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
